In [49]:
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import VarianceThreshold
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt

In [16]:
import tensorflow as tf

In [3]:
X = np.load('clean_data/X.npy')
y = np.load('clean_data/y.npy')

In [57]:
selector = VarianceThreshold(threshold= .01)

X_reduced = selector.fit_transform(X)

: 

In [ ]:
X_reduced.shape

(31011, 8679)

In [56]:
X_reduced.shape

(31011, 2546)

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Data pipelining

In [20]:
#Scale the data
scaler = StandardScaler()
scaled_X_train = scaler.fit_transform(X_train)

In [44]:
np.max(scaled_X_train, axis=1)

array([ 8.56299833, 68.39584714, 64.2935974 , ...,  5.70255434,
       90.9303763 ,  4.57839747])

In [45]:
np.max(X_train, axis=1)

array([ 53.,  17.,  93., ...,  47., 462., 202.])

In [48]:
np.max(scaled_X_train, axis=1)

array([ 8.56299833, 68.39584714, 64.2935974 , ...,  5.70255434,
       90.9303763 ,  4.57839747])

In [ ]:
train_ds = tf.data.Dataset.from_tensor_slices({'data':  X_train, 
                                               'label': y_train})

In [6]:
AUTOTUNE = tf.data.AUTOTUNE
batch_size = 32

In [12]:
it = iter(train_ds)
dat = it.next()

In [ ]:
train_ds = train_ds.cache() \
                   .shuffle(buffer_size=len(X_train)) \
                   .batch(batch_size) \
                   .prefetch(AUTOTUNE)

Cause: for/else statement not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Cause: for/else statement not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


NotImplementedError: in user code:

    File "/tmp/ipykernel_4419/246526946.py", line 4, in standard_scale  *
        genes = scaler.fit_transform(ds['data'])
    File "/root/projects/tf217/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 865, in wrapped  *
        data_to_wrap = f(self, X, *args, **kwargs)
    File "/root/projects/tf217/lib/python3.12/site-packages/sklearn/base.py", line 917, in fit_transform  *
        return self.fit(X, **fit_params).transform(X)
    File "/root/projects/tf217/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit  *
        return self.partial_fit(X, y, sample_weight)
    File "/root/projects/tf217/lib/python3.12/site-packages/sklearn/base.py", line 913, in wrapper  *
        return fit_method(estimator, *args, **kwargs)
    File "/root/projects/tf217/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit  *
        X = validate_data(
    File "/root/projects/tf217/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2943, in validate_data  *
        out = check_array(X, input_name="X", **check_params)
    File "/root/projects/tf217/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array  *
        array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
    File "/root/projects/tf217/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order  *
        array = numpy.asarray(array, order=order, dtype=dtype)

    NotImplementedError: Cannot convert a symbolic tf.Tensor (args_0:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported.
